benchmarks:
  metrics:                    # default metrics by dataset type (as listed by amlb.data.DatasetType)
    binary: ['bac', 'auc', 'acc']
    multiclass: ['bac', 'logloss', 'acc']
    regression: ['rmse', 'r2']
  constraints_file:
    - '{root}/resources/constraints.yaml'
    - '{user}/constraints.yaml'

frameworks:
  definition_file:  # this allows to add custom framework definitions (in {user}/frameworks.yaml) on top of the default ones.
    - '{root}/resources/frameworks.yaml'
    - '{user}/frameworks.yaml'
